; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed-xiao-rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino
monitor_speed = 115200
upload_protocol = mbed

upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

board_build.core = earlephilhower
board_build.filesystem = littlefs
board_build.flash_size = 2m
board_build.filesystem_size = 1m
board_build.arduino.earlephilhower.partition = 1m1m
lib_deps = 
    adafruit/Adafruit NeoPixel @ ^1.12.0